name: Provision aws aurora
on:
  push:
    branches:
      - main

env:
  WORKSPACE: prod  
  AWS_REGION : "us-east-1"
  ROLE_TO_ASSUME: arn:aws:iam::826972386494:role/github-actions-andreelidio
  TERRAFORM_VERSION: "1.4.0"

permissions:
  id-token: write   
  contents: read 

jobs:
  setup:
    name: Setup Terraform and AWS
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ steps.set-workspace.outputs.workspace }}

    steps:                       
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: ${{env.TERRAFORM_VERSION}}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.ROLE_TO_ASSUME}}
          role-session-name: NAME
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Terraform Workspace
        id: set-workspace
        run: echo "workspace=${{ env.WORKSPACE }}" >> $GITHUB_ENV

  deploy-aurora:
    needs: setup
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List directories and files
        run: ls -R
        shell: bash

      - name: Initialize Terraform in the Aurora module
        run: |
          if [ -d "modules/aurora/" ]; then
            echo "Directory modules/aurora/ found."
            cd modules/aurora/ && terraform init
          else
            echo "Directory modules/aurora/ does not exist. Listing current directory structure:"
            ls -R
            exit 1
          fi

      - name: Terraform Init aws aurora
        run: |
          cd modules/aurora/ && terraform init

      - name: Select Terraform Workspace aws aurora
        run: |
          cd modules/aurora/ && terraform workspace select ${{ env.WORKSPACE }} || terraform workspace new ${{ env.WORKSPACE }}

      - name: Terraform Fmt aws aurora
        run: |
          cd modules/aurora/ && terraform fmt -check

      - name: Terraform Validate aws aurora
        run: |
          cd modules/aurora/ && terraform validate -no-color

      - name: Terraform Plan aws aurora
        run: |
          cd modules/aurora/tfvars && terraform plan -var-file=tfvars/sns.tfvars -no-color

      - name: Apply aws aurora infrastructure
        run: |
          cd modules/aurora/tfvars && terraform apply -var-file=tfvars/sns.tfvars -auto-approve

  